### ISSUE TITLE
abs_cat_stats is giving a "Error in seq_len(nrow(z)) error for some ABS catalogues

### ISSUE THREAD

**Issue by rowem** [mitcda/raustats#1]
I copied the first line below from the :Package ‘raustats’
March 13, 2019" pdf into R and it works.
I then modified it for catalogue 8731.0, but I cannot get it to work, other than for all Tables (i.e. 2nd line below)

ana_q <- abs_cat_stats("5206.0", tables=c("Table 1\\W+", "Table 2\\W+"))  #  this works
ana_q <- abs_cat_stats("8731.0", tables= "All" )                          # this works
ana_q <- abs_cat_stats("8731.0", tables=c("TABLE 01\\W+", "TABLE 02\\W+"))  #  this DOES NOT work
ana_q <- abs_cat_stats("8731.0", tables= c("TABLE 01[ .]+", "TABLE 02[ .]+"))  # this DOES NOT work

It appears to download (i.e. horizontal string of "="s appear but then gives an error message.
This is the error message:
"Error in seq_len(nrow(z)) : 
  argument must be coercible to non-negative integer
In addition: Warning message:
In seq_len(nrow(z)) : first element used of 'length.out' argument"

I have googled this but nothing is helping to resolve it.  
Any help resolving this would be appreciated.

Note:  Windows 10 / R-3.6.1  (also tried Microsoft\R Open\R-3.5.3  but same error)

**Comment by mitcda** [comment]
Revised `abs_cat_tables` function to handle errors thrown by `abs_cat_tables` and `abs_cat_stats` for some ABS Catalogue no. (e.g. 8731.0 and 3105.0.65.001) in development version (and next release 0.15).
